version: '3'
services:
  docker-js-dev:
    image: node:latest
    volumes:
      - ./src:/src
      - ./scripts:/scripts
      - ./.vscode:/.vscode
    working_dir: /src
    command: /scripts/start.sh
    ports:
      - 1234:1234
      - 1235:1235
    environment:
      DOCKER_GATEWAY_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}